# MCDI500 — Programación para Datos
## Evaluación Sumativa 2 — Fase 2: Pipeline de Obtención, Limpieza y Transformación de Datos

**Proyecto:** Optimización del OEE mediante Mantenimiento Predictivo Inteligente en Activos Críticos Industriales <br>
**Grupo 7:** Alana Bermúdez · Gonzalo Mansilla · Eduardo Villalón <br>
**Docente:** Dr. Omar Salinas Silva

# I. Introducción y Propósito de la Fase 2
Este notebook implementa el pipeline de ingeniería de datos para el procesamiento de variables operacionales y registros de fallas mecánicas. El objetivo técnico es transformar el conjunto de datos crudos (*raw data*) en una matriz limpia, tipificada y estructurada en el directorio `data/processed/`, garantizando la reproducibilidad y consistencia analítica requerida para las fases de modelamiento predictivo (Salinas Silva, 2026b).

# II. Configuración del Entorno e Imports

In [1]:
!pip install seaborn

Requirement already satisfied: seaborn in c:\users\gmansilla\appdata\local\programs\python\python314\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\gmansilla\appdata\local\programs\python\python314\lib\site-packages (from seaborn) (2.4.1)
Requirement already satisfied: pandas>=1.2 in c:\users\gmansilla\appdata\local\programs\python\python314\lib\site-packages (from seaborn) (3.0.0)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\gmansilla\appdata\local\programs\python\python314\lib\site-packages (from seaborn) (3.10.9)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\gmansilla\appdata\local\programs\python\python314\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\gmansilla\appdata\local\programs\python\python314\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\gmansilla\appdata\local\programs\python\python314\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\gmansilla\appdata\local\programs\python\python314\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\gmansilla\appdata\local\programs\python\python314\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.2)
Requirement already satisfied: pillow>=8 in c:\users\gmansilla\appdata\local\programs\python\python314\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.2.0)
Requirement already satisfied: pyparsing>=3 in c:\users\gmansilla\appdata\local\programs\python\python314\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\gmansilla\appdata\local\programs\python\python314\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\gmansilla\appdata\local\programs\python\python314\lib\site-packages (from pandas>=1.2->seaborn) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\gmansilla\appdata\local\programs\python\python314\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns

# Configuración global de estilos para gráficos
sns.set_theme(style="whitegrid")

print("Librerías importadas y entorno configurado correctamente.")

Librerías importadas y entorno configurado correctamente.

# III. Obtención de Datos

In [3]:
# Definición de la función para mayor modularidad
def cargar_datos(nombre_archivo):
    ruta = Path.cwd().parent / "data" / "raw" / nombre_archivo
    print("Ruta usada:", ruta)
    return pd.read_csv(ruta)

# Ejecución de la carga
df = cargar_datos("predictive_maintenance_dataset.csv")

print("Dataset cargado satisfactoriamente.")
display(df.head())

Ruta usada: C:\Python\mcdi500_s1_grupo7\data\raw\predictive_maintenance_dataset.csv
Dataset cargado satisfactoriamente.

,date,device,failure,metric1,metric2,metric3,metric4,metric5,metric6,metric7,metric8,metric9
0,1/1/2015,S1F01085,0,215630672,55,0,52,6,407438,0,0,7
1,1/1/2015,S1F0166B,0,61370680,0,3,0,6,403174,0,0,0
2,1/1/2015,S1F01E6Y,0,173295968,0,0,0,12,237394,0,0,0
3,1/1/2015,S1F01JE0,0,79694024,0,0,0,6,410186,0,0,0
4,1/1/2015,S1F01R2B,0,135970480,0,0,0,15,313173,0,0,3

# IV. Diagnóstico de Calidad

In [4]:
# Resumen estadístico
print("Resumen estadístico de los datos:")
display(df.describe())

Resumen estadístico de los datos:

,failure,metric1,metric2,metric3,metric4,metric5,metric6,metric7,metric8,metric9
count,124494.000000,1.244940e+05,124494.000000,124494.000000,124494.000000,124494.000000,124494.000000,124494.000000,124494.000000,124494.000000
mean,0.000851,1.223881e+08,159.492706,9.940897,1.741120,14.222669,260172.657726,0.292528,0.292528,13.013848
std,0.029167,7.045933e+07,2179.677781,185.748131,22.908507,15.943028,99151.078547,7.436924,7.436924,275.661220
min,0.000000,0.000000e+00,0.000000,0.000000,0.000000,1.000000,8.000000,0.000000,0.000000,0.000000
25%,0.000000,6.128476e+07,0.000000,0.000000,0.000000,8.000000,221452.000000,0.000000,0.000000,0.000000
50%,0.000000,1.227974e+08,0.000000,0.000000,0.000000,10.000000,249799.500000,0.000000,0.000000,0.000000
75%,0.000000,1.833096e+08,0.000000,0.000000,0.000000,12.000000,310266.000000,0.000000,0.000000,0.000000
max,1.000000,2.441405e+08,64968.000000,24929.000000,1666.000000,98.000000,689161.000000,832.000000,832.000000,70000.000000

In [5]:
# Diagnóstico adicional de calidad
print("--- Valores Nulos ---")
print(df.isnull().sum())

print("\n--- Duplicados ---")
print(f"Total registros duplicados: {df.duplicated().sum()}")

print("\n--- Tipos de Datos ---")
print(df.dtypes)

--- Valores Nulos ---
date       0
device     0
failure    0
metric1    0
metric2    0
metric3    0
metric4    0
metric5    0
metric6    0
metric7    0
metric8    0
metric9    0
dtype: int64

--- Duplicados ---
Total registros duplicados: 1

--- Tipos de Datos ---
date         str
device       str
failure    int64
metric1    int64
metric2    int64
metric3    int64
metric4    int64
metric5    int64
metric6    int64
metric7    int64
metric8    int64
metric9    int64
dtype: object

In [6]:
from pathlib import Path

print("Ruta actual de trabajo:")
print(Path.cwd())

Ruta actual de trabajo:
C:\Python\mcdi500_s1_grupo7\notebooks

In [7]:
print("Cantidad de filas:", df.shape[0])

print("\nCantidad de duplicados:")
print(df.duplicated().sum())

print("\nRegistros duplicados:")
display(df[df.duplicated()])

Cantidad de filas: 124494

Cantidad de duplicados:
1

Registros duplicados:

,date,device,failure,metric1,metric2,metric3,metric4,metric5,metric6,metric7,metric8,metric9
101335,7/10/2015,S1F0R4Q8,0,192721392,0,0,0,8,213700,0,0,0

In [8]:
# Crear copia antes (buena práctica)
df_before = df.copy()

# Eliminar duplicados
df = df.drop_duplicates()

print("Duplicados eliminados correctamente.")

Duplicados eliminados correctamente.

In [9]:
print("Filas antes:", df_before.shape[0])
print("Filas después:", df.shape[0])

print("\nDuplicados restantes:")
print(df.duplicated().sum())

Filas antes: 124494
Filas después: 124493

Duplicados restantes:
0

In [10]:
# Ver tipo antes
print("Tipo antes:")
print(df["date"].dtype)

# Convertir a datetime
df["date"] = pd.to_datetime(df["date"])

# Ver tipo después
print("\nTipo después:")
print(df["date"].dtype)

Tipo antes:
str

Tipo después:
datetime64[us]

In [11]:
# Crear nuevas variables de tiempo
df["year"] = df["date"].dt.year
df["month"] = df["date"].dt.month
df["day"] = df["date"].dt.day

print("Variables temporales creadas correctamente.")

Variables temporales creadas correctamente.

In [13]:
display(df.head())

,date,device,failure,metric1,metric2,metric3,metric4,metric5,metric6,metric7,metric8,metric9,year,month,day
0,2015-01-01,S1F01085,0,215630672,55,0,52,6,407438,0,0,7,2015,1,1
1,2015-01-01,S1F0166B,0,61370680,0,3,0,6,403174,0,0,0,2015,1,1
2,2015-01-01,S1F01E6Y,0,173295968,0,0,0,12,237394,0,0,0,2015,1,1
3,2015-01-01,S1F01JE0,0,79694024,0,0,0,6,410186,0,0,0,2015,1,1
4,2015-01-01,S1F01R2B,0,135970480,0,0,0,15,313173,0,0,3,2015,1,1

In [14]:
print("VALIDACIÓN FINAL DEL DATASET\n")

print("Filas iniciales:", df_before.shape[0])
print("Filas finales:", df.shape[0])

print("\nDuplicados restantes:")
print(df.duplicated().sum())

print("\nTipos de datos finales:")
print(df.dtypes)

print("\nResumen estadístico:")
display(df.describe())

VALIDACIÓN FINAL DEL DATASET

Filas iniciales: 124494
Filas finales: 124493

Duplicados restantes:
0

Tipos de datos finales:
date       datetime64[us]
device                str
failure             int64
metric1             int64
metric2             int64
metric3             int64
metric4             int64
metric5             int64
metric6             int64
metric7             int64
metric8             int64
metric9             int64
year                int32
month               int32
day                 int32
dtype: object

Resumen estadístico:

,date,failure,metric1,metric2,metric3,metric4,metric5,metric6,metric7,metric8,metric9,year,month,day
count,124493,124493.000000,1.244930e+05,124493.000000,124493.000000,124493.000000,124493.000000,124493.000000,124493.000000,124493.000000,124493.000000,124493.0,124493.000000,124493.000000
mean,2015-04-16 05:19:50.900693,0.000851,1.223875e+08,159.493988,9.940977,1.741134,14.222719,260173.031022,0.292531,0.292531,13.013953,2015.0,4.028275,14.894235
min,2015-01-01 00:00:00,0.000000,0.000000e+00,0.000000,0.000000,0.000000,1.000000,8.000000,0.000000,0.000000,0.000000,2015.0,1.000000,1.000000
25%,2015-02-09 00:00:00,0.000000,6.128346e+07,0.000000,0.000000,0.000000,8.000000,221452.000000,0.000000,0.000000,0.000000,2015.0,2.000000,7.000000
50%,2015-03-27 00:00:00,0.000000,1.227971e+08,0.000000,0.000000,0.000000,10.000000,249800.000000,0.000000,0.000000,0.000000,2015.0,3.000000,15.000000
75%,2015-06-17 00:00:00,0.000000,1.833091e+08,0.000000,0.000000,0.000000,12.000000,310266.000000,0.000000,0.000000,0.000000,2015.0,6.000000,22.000000
max,2015-11-02 00:00:00,1.000000,2.441405e+08,64968.000000,24929.000000,1666.000000,98.000000,689161.000000,832.000000,832.000000,70000.000000,2015.0,11.000000,31.000000
std,NaN,0.029167,7.045934e+07,2179.686488,185.748875,22.908598,15.943082,99151.389285,7.436954,7.436954,275.662324,0.0,2.572164,8.759566

In [17]:
# Crear carpeta processed si no existe
ruta_carpeta = Path.cwd().parent / "data" / "processed"
ruta_carpeta.mkdir(parents=True, exist_ok=True)

# Ruta del archivo final
ruta_salida = ruta_carpeta / "dataset_procesado.csv"

# Guardar archivo
df.to_csv(ruta_salida, index=False)

print("Dataset exportado correctamente en:")
print(ruta_salida)

Dataset exportado correctamente en:
C:\Python\mcdi500_s1_grupo7\data\processed\dataset_procesado.csv